lang: ja
title: なでしこーだー
description: 日本語プログラミング言語「なでしこ３」でAtCoderの問題を解くためのchrome拡張機能
theme: jekyll-theme-slate
show_downloads: true
google_analytics: G-G0QKGE4TT9
github:
  is_project_page: true
plugins:
  - jekyll-sitemap
